import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = {x = 8, y = 4}
dynamic_padding = true
decorations = "None"
opacity = 0.9
blur = true


[font]
# normal = {family = "MesloLGS NF", style = "Regular"}
# offset= {x=0, y=12}
# glyph_offset= {x=0, y=6}
normal = {family = "CaskaydiaCove Nerd Font", style = "Regular"}
size = 16.0




