color = ''
project-name = 'default'
[default]
account_id = 'acct_1N3GCuGqCC0x0Xxs'
device_name = 'Brians-MacBook-Pro.local'
display_name = 'eleno.net'
live_mode_api_key = 'rk_live_***********************************************************************************************yTyV'
live_mode_key_expires_at = '2025-04-08'
live_mode_pub_key = 'pk_live_51N3GCuGqCC0x0XxsvWz6ZjMBnfeBGATKDxu0HnLHRbe7Xq8d1XNZAxtu1hHQJIoLLCB9nn6TdvWETtpqxh6whaId00IrNqkS7M'
test_mode_api_key = 'rk_test_51N3GCuGqCC0x0Xxs5Q4HQgeDA23hfoUA7z9SEehEGw6vokWIimteAKAKDmByZK2DF1zW62a4KrPWpVD0tNqojRQG00SE5NcszL'
test_mode_key_expires_at = '2025-04-08'
test_mode_pub_key = 'pk_test_51N3GCuGqCC0x0XxszRopqIgQB9mcmJ9ayYLxjYSjAu0Oxk0hPcYboKEgUMsHPQVNdOJtUk8w68R1ok7aLlAa0OnP00opM2y7Kl'

