color = ''
project-name = 'default'
[default]
account_id = 'acct_1N3GCuGqCC0x0Xxs'
device_name = 'Brians-MacBook-Pro.local'
display_name = 'eleno.net'
live_mode_api_key = 'rk_live_***********************************************************************************************IaXT'
live_mode_key_expires_at = '2025-01-02'
live_mode_pub_key = 'pk_live_51N3GCuGqCC0x0XxsvWz6ZjMBnfeBGATKDxu0HnLHRbe7Xq8d1XNZAxtu1hHQJIoLLCB9nn6TdvWETtpqxh6whaId00IrNqkS7M'
test_mode_api_key = 'rk_test_51N3GCuGqCC0x0XxsJb4Aev93p476fc7cc6kyyxeBfZgFzLBwL84uIwwWEaFBA2UP0qb5sw1xeK5Fjgjk8IuuKu1n00YBeoWcvX'
test_mode_key_expires_at = '2025-01-02'
test_mode_pub_key = 'pk_test_51N3GCuGqCC0x0XxszRopqIgQB9mcmJ9ayYLxjYSjAu0Oxk0hPcYboKEgUMsHPQVNdOJtUk8w68R1ok7aLlAa0OnP00opM2y7Kl'

